### ISSUE TITLE
RecyclerView没有管理者

### ISSUE THREAD

**Issue by XieYiGod** [idic779/monthweekmaterialcalendarview#4]
你好，我把你的布局文件复制到我的项目中运行就会报RecyclerView没有LinearLayout管理者的错误。
你的自定义控件中没有加管理者吗？
还是我需我怎么做？

**Comment by idic779** [comment]
@XieYiGod  目前底部的RecyclerView只支持线性LinearLayoutManager，稍后完善下添加其他layoutManager

**Comment by idic779** [comment]
V1.7已添加
