### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by zr940326** [idic779/monthweekmaterialcalendarview#6]
作者你好，我想问下，如何结合你的控件，让我的下拉刷新起作用。
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:ptr="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:id="@+id/linearlayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="64dp"
            android:background="@drawable/bar_shape"
            android:orientation="vertical">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="44dp"
                android:layout_marginTop="20dp"
                android:gravity="center_vertical">

                <ImageView
                    android:id="@+id/tool_bar_back"
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                    android:layout_centerVertical="true"
                    android:layout_marginLeft="5dp"
                    android:paddingBottom="10dp"
                    android:paddingRight="10dp"
                    android:paddingTop="10dp"
                    android:src="@mipmap/ic_tool_bar_back" />

                <TextView
                    android:id="@+id/tool_bar_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:layout_centerVertical="true"
                    android:singleLine="true"
                    android:text=""
                    android:textColor="#FFFFFF"
                    android:textSize="18sp" />

                <TextView
                    android:id="@+id/tool_bar_righttext"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentRight="true"
                    android:layout_centerVertical="true"
                    android:layout_marginRight="15dp"
                    android:drawablePadding="3dp"
                    android:ellipsize="end"
                    android:maxWidth="80dp"
                    android:singleLine="true"
                    android:text=""
                    android:textColor="#FFFFFF"
                    android:textSize="16sp" />

            </RelativeLayout>

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="10dp"
            android:layout_marginTop="10dp"
            android:orientation="horizontal">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="35dp"
                android:layout_weight="1"
                android:gravity="center_vertical"
                android:orientation="horizontal">

                <TextView
                    android:id="@+id/tv_qh_syyear"
                    android:layout_width="50dp"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="15dp"
                    android:background="#ECF0FB"
                    android:gravity="center"
                    android:text="《" />

                <TextView
                    android:id="@+id/tv_show_year"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:text="年份" />

                <TextView
                    android:id="@+id/tv_qh_xyyear"
                    android:layout_width="50dp"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="15dp"
                    android:background="#ECF0FB"
                    android:gravity="center"
                    android:text="》" />
                />
            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="35dp"
                android:layout_weight="1"
                android:gravity="center_vertical"
                android:orientation="horizontal">

                <TextView
                    android:id="@+id/tv_qh_sygyue"
                    android:layout_width="50dp"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="15dp"
                    android:background="#ECF0FB"
                    android:gravity="center"
                    android:text="《" />

                <TextView
                    android:id="@+id/tv_show_yf"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:text="月份" />

                <TextView
                    android:id="@+id/tv_qh_xygyue"
                    android:layout_width="50dp"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="15dp"
                    android:layout_marginRight="15dp"
                    android:background="#ECF0FB"
                    android:gravity="center"
                    android:text="》" />
                />
            </LinearLayout>
        </LinearLayout>

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/tv_selectdate"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:gravity="center"
                android:text="日期" />

            <TextView
                android:id="@+id/qh_switch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_marginRight="15dp"
                android:gravity="center"
                android:text="开/关"
                android:textColor="#333"
                android:visibility="visible" />

        </RelativeLayout>

    </LinearLayout>

    <com.bykj.sharelib.applib.calendar.amm.MonthWeekMaterialCalendarView
        android:id="@+id/monthWeekMaterialCalendarView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/linearlayout">

        <com.bykj.sharelib.applib.calendar.pm.MaterialCalendarView
            android:id="@+id/calendarView_month_mode"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:mcv_calendarMode="month"
            app:mcv_showLunar="false"
            app:mcv_showOtherDates="defaults|other_months"
            app:mcv_showWeekView="false" />

        <com.bykj.sharelib.applib.calendar.pm.MaterialCalendarView
            android:id="@+id/calendarView_week_mode"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/white"
            android:visibility="invisible"
            app:mcv_calendarMode="week"
            app:mcv_showLunar="false"
            app:mcv_showTopBar="false"
            app:mcv_showWeekView="false" />

        <com.bykj.sharelib.appview.LoadingLayout
            android:id="@+id/loading_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <com.bykj.sharelib.applib.refresh.PtrClassicFrameLayout
                android:id="@+id/ptr_refresh_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                ptr:ptr_duration_to_close_either="1000"
                ptr:ptr_keep_header_when_refresh="true"
                ptr:ptr_pull_to_fresh="false"
                ptr:ptr_ratio_of_header_height_to_refresh="1.2"
                ptr:ptr_resistance="1.7">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recyclerView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginTop="10dp"
                    android:background="@android:color/white"
                    android:orientation="vertical" />
            </com.bykj.sharelib.applib.refresh.PtrClassicFrameLayout>
        </com.bykj.sharelib.appview.LoadingLayout>

        <LinearLayout
            android:id="@+id/weekview_top"
            android:layout_width="match_parent"
            android:layout_height="44dp"
            android:background="#ECF0FB"
            android:orientation="horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周日" />

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周一" />

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周二" />

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周三" />

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周四" />

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周五" />

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center"
                android:text="周六" />

        </LinearLayout>
    </com.bykj.sharelib.applib.calendar.amm.MonthWeekMaterialCalendarView>

</RelativeLayout>

我的rv最外面，要套一层下拉刷新和加载布局，我发现现在不能怎么做，我的下拉刷新都不起作用，我尝试修改过，MonthWeekMaterialCalendarView中的 onFinishInflate方法：
@Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        mCalendarViewMonth = (MaterialCalendarView) getChildAt(0);
        mCalendarViewWeek = (MaterialCalendarView) getChildAt(1);
        loadingLayout = (LoadingLayout) getChildAt(2);
        ptr_refresh_layout = (PtrClassicFrameLayout) loadingLayout.getChildAt(7);
        mRecyclerView = (RecyclerView) ptr_refresh_layout.getChildAt(2);
        mRecyclerView = (RecyclerView) getChildAt(2);
        mTopWeekView = getChildAt(3);
        mCalendarViewMonth.setTopbarVisible(false);
        newState().commit();
        setListener();
    }
结果还是无用

**Comment by zr940326** [comment]
该问题，已经解决，去掉了LoadingLayout ，就能显示下拉刷新了，然后，需要在onLayout中，重新加载

**Comment by idic779** [comment]
好的@zr940326
